export type Vehicle = {
  id: string,
  VIN: string,
  Manufacturer: string,
  ModelYear: number,
  OdoMiles?: number,
  Region?: string,
  Vocation?: string,
  FleetName?: string,
  AdditionalParameter?: string,
  EngSerialNum: number,
  EngManufacturer: string,
  EngModel: string,
  EngModelYear: number,
  FuelType?: string,
  Displacement?: string,
  EngAdditionalParameter?: string,
  TransmissonType: string,
  TransManufacturer: string,
  TransModel: string,
  Hybrid?: string,
  DOC?: boolean,
  TWC?: boolean,
  SCR?: boolean,
  PMTrap?: boolean
};