/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:afdbd7f1-97f7-420c-bebc-48070bbede6a",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_hZZ6MguxX",
    "aws_user_pools_web_client_id": "64ukb8e2v3rva07r6l25bncj21",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://f25om5egfbalteodjso34thqim.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
